var N = null;var sourcesIndex = {};
sourcesIndex["anyhow"] = {"name":"","files":["backtrace.rs","chain.rs","context.rs","ensure.rs","error.rs","fmt.rs","kind.rs","lib.rs","macros.rs","ptr.rs","wrapper.rs"]};
sourcesIndex["bitflags"] = {"name":"","files":["lib.rs"]};
sourcesIndex["heck"] = {"name":"","files":["camel.rs","kebab.rs","lib.rs","mixed.rs","shouty_kebab.rs","shouty_snake.rs","snake.rs","title.rs"]};
sourcesIndex["id_arena"] = {"name":"","files":["lib.rs"]};
sourcesIndex["memchr"] = {"name":"","dirs":[{"name":"memchr","dirs":[{"name":"x86","files":["avx.rs","mod.rs","sse2.rs"]}],"files":["fallback.rs","iter.rs","mod.rs","naive.rs"]},{"name":"memmem","dirs":[{"name":"prefilter","dirs":[{"name":"x86","files":["avx.rs","mod.rs","sse.rs"]}],"files":["fallback.rs","genericsimd.rs","mod.rs"]},{"name":"x86","files":["avx.rs","mod.rs","sse.rs"]}],"files":["byte_frequencies.rs","genericsimd.rs","mod.rs","rabinkarp.rs","rarebytes.rs","twoway.rs","util.rs","vector.rs"]}],"files":["cow.rs","lib.rs"]};
sourcesIndex["pulldown_cmark"] = {"name":"","files":["entities.rs","escape.rs","html.rs","lib.rs","linklabel.rs","parse.rs","puncttable.rs","scanners.rs","strings.rs","tree.rs"]};
sourcesIndex["tinyvec"] = {"name":"","dirs":[{"name":"array","files":["generated_impl.rs"]}],"files":["array.rs","arrayvec.rs","arrayvec_drain.rs","lib.rs","slicevec.rs","tinyvec.rs"]};
sourcesIndex["tinyvec_macros"] = {"name":"","files":["lib.rs"]};
sourcesIndex["unicase"] = {"name":"","dirs":[{"name":"unicode","files":["map.rs","mod.rs"]}],"files":["ascii.rs","lib.rs"]};
sourcesIndex["unicode_normalization"] = {"name":"","files":["__test_api.rs","decompose.rs","lib.rs","lookups.rs","no_std_prelude.rs","normalize.rs","perfect_hash.rs","quick_check.rs","recompose.rs","replace.rs","stream_safe.rs","tables.rs"]};
sourcesIndex["unicode_segmentation"] = {"name":"","files":["grapheme.rs","lib.rs","sentence.rs","tables.rs","word.rs"]};
sourcesIndex["unicode_xid"] = {"name":"","files":["lib.rs","tables.rs"]};
sourcesIndex["wit_bindgen_gen_core"] = {"name":"","files":["lib.rs","ns.rs"]};
sourcesIndex["wit_bindgen_gen_rust"] = {"name":"","files":["lib.rs"]};
sourcesIndex["wit_bindgen_gen_wasm3"] = {"name":"","files":["lib.rs"]};
sourcesIndex["wit_bindgen_wasm3"] = {"name":"","files":["lib.rs"]};
sourcesIndex["wit_bindgen_wasm3_impl"] = {"name":"","files":["lib.rs"]};
sourcesIndex["wit_parser"] = {"name":"","dirs":[{"name":"ast","files":["lex.rs","resolve.rs"]}],"files":["abi.rs","ast.rs","lib.rs","sizealign.rs"]};
createSourceSidebar();
